INSERT INTO onlinestore.product (name,price,discount,rating,age,piece_count,availability,description,theme_id,picture_url1,picture_url2,picture_url3) VALUES
	 ('Dubai',59.99,0,9.0,16,740,'Available now','Share a photo of your favorite LEGO creations, we''d love to see how you''ve made it your own. Mention @lego on your Instagram posts to get your photo featured in our showcase.',1,'http://localhost:5000/images/dubai_21052_1.jpg','http://localhost:5000/images/dubai_21052_2.jpg','http://localhost:5000/images/dubai_21052_3.jpg'),
	 ('Paris',49.99,0,9.0,12,649,'Available now','Bring together iconic Paris landmarks with this magnificent Paris skyline model. The 21044 LEGO® Architecture Skyline Collection set features the Arc de Triomphe, Champs-Elysées, Tour Montparnasse, Grand Palais, Eiffel Tower and the Louvre, and is finished with grass and tree areas and a decorative Paris nameplate. This set has been designed to deliver a rewarding and relaxing building experience to all with an interest in architecture, travel, history and design, and makes a truly “magnifique” centerpiece for the home or office. Each skyline model is scaled to give an accurate representation of the comparative size of the featured structures, with realistic color depiction.',1,'http://localhost:5000/images/paris_21045_1.jpg','http://localhost:5000/images/paris_21045_2.jpg','http://localhost:5000/images/paris_21045_3.jpg'),
	 ('Taj Mahal',119.99,0,10.0,18,2022,'Available now','The Taj Mahal model features a wealth of rich details, including sweeping arches, ornate domes, soaring minarets and decorative finials. The LEGO Taj Mahal expert building kit can be build together with all other original LEGO sets and LEGO bricks, including other collectible building kits.',1,'http://localhost:5000/images/Taj_Mahal_21056_1.jpg','http://localhost:5000/images/Taj_Mahal_21056_2.jpg','http://localhost:5000/images/Taj_Mahal_21056_3.jpg'),
	 ('Farm Animal Care',9.99,0,10.0,2,11,'Upon order','The versatile LEGO® DUPLO® Town Farm Animal Care (10949) playset engages toddlers with imaginative play and encourages key developmental skills with the help of 4 adorable farm animals.

Build skills with toddler-friendly animals
Parents and toddlers will enjoy endless imaginative fun with the delightful pig, sheep, duck and cat. These 4 cute farm animals are perfect for preschoolers to pick up and play with. As they act out animal-care activities, such as feeding and preparing the barn for bedtime, little animal lovers will improve their fine motor skills and their social and emotional awareness.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/animalele_de_la_ferma_10949_1.jpg','http://localhost:5000/images/animalele_de_la_ferma_10949_2.jpg','http://localhost:5000/images/animalele_de_la_ferma_10949_3.jpg'),
	 ('Airplane & Airport',29.99,0,0.0,2,28,'Coming soon','Take a toddler''s imagination to a different destination every day with the LEGO® DUPLO® Town aeroplane & Airport (10961) toy. Share air-travel adventures with your preschooler Capture all the exciting adventures and family fun of a flight aboard a passenger aeroplane. Join a dad and his daughter as they fly off to see family and friends. The plane has a lift-off top section to reveal more space to play inside. The airport has an opening door and a turning control tower, a luggage slide and… big hugs waiting to greet your arrival! Hands-on educational toys for toddlers LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/Avion_si_aeroport_10961_1.jpg','http://localhost:5000/images/Avion_si_aeroport_10961_2.jpg','http://localhost:5000/images/Avion_si_aeroport_10961_3.jpg'),
	 ('Spider-Man Headquarters
',29.99,0,0.0,2,36,'Coming soon','LEGO® DUPLO® Marvel Spider-Man Headquarters (10940) is the perfect treat for a budding superhero. With 3 superhero figures and lots of super-fun activities, this versatile playset delivers excellent play value.

Fun-packed action with Spider-Man and friends
Based on the Disney+ TV show, Spidey and His Amazing Friends, this toddler-friendly superhero set combines the fun and adventure of the TV program with the hands-on, developmental benefits of LEGO DUPLO construction. The set features 3 superheroes – Spider-Man, Miles Morales and Ghost Spider – in their spider-shaped headquarters with fun accessories to inspire imaginative role play, including a motorcycle, slide and a rope swing.

Hands-on, imaginative role-play toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands, so parents and toddlers can share many precious developmental moments together.',7,'http://localhost:5000/images/Cartierul_general_al_Omului_Paianjen_10940_1.jpg','http://localhost:5000/images/Cartierul_general_al_Omului_Paianjen_10940_2.jpg','http://localhost:5000/images/Cartierul_general_al_Omului_Paianjen_10940_3.jpg'),
	 ('Ariel''s Undersea Castle
',29.99,0,0.0,2,35,'Upon order','LEGO® DUPLO® │ Disney Ariel''s Undersea Castle (10922) entertains and stimulates young minds, developing social and emotional skills with a mermaid''s playground full of fun features and role-play stories.',7,'http://localhost:5000/images/castelul_lui_ariel_10922_1.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_2.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_3.jpg'),
	 ('Heart Box',19.99,0,7.0,2,80,'Available now','This exciting mix of LEGO® DUPLO® bricks is bursting with ideas and inspiration! As parents and toddlers build, play and build again, this imaginative learning toy will kickstart kids’ creative building and deliver developmental benefits that last a lifetime. Unleash kids'' creativity with this stimulating starter set Little hands can''t wait to get hold of the toddler-friendly bricks and start building. Simple instructions ensure the imaginative play starts without delay. There''s a house, ice cream, whale, flower, helicopter and duck Each easy-to-build model provides lots to talk about and imaginative stories to role-play. The creative fun continues as kids mix the bricks to build their own creations. Build valuable skills a first LEGO DUPLO set LEGO DUPLO playsets put open-ended play and self-expression into the hands of budding builders. With recognizable settings, familiar characters and toddler-friendly bricks, they inspire preschoolers with a boundless enthusiasm for playful learning.',7,'http://localhost:5000/images/castelul_lui_ariel_10922_1.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_2.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_3.jpg'),
	 ('T. rex and Triceratops Dinosaur Breakout',29.99,0,0.0,2,36,'Coming soon','This LEGO® DUPLO® Jurassic World T. rex and Triceratops Dinosaur Breakout (10939) toy is packed with fun features and Jurassic World movie action that’ll make dinosaur-loving kids roar with delight.

Developmental dinosaur playset
When a T. rex bursts through the iconic gates of Jurassic World, preschool dinosaur fans must help Owen rescue the baby triceratops and take it to safety on his motorcycle. From the entrance''s opening gates to the T. rex''s opening mouth; the high-voltage fence to the cool motorcycle with room on the seat for Owen and the baby triceratops – this playset is bursting with exciting action and fun features that develop kids’ construction and creative-thinking skills and fuel their imaginations.

Hands-on, imaginative role-play toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands, so parents and toddlers can share many precious developmental moments together.',7,'http://localhost:5000/images/Evadarea_dinozaurilor_10939_1.jpg','http://localhost:5000/images/Evadarea_dinozaurilor_10939_2.jpg','http://localhost:5000/images/Evadarea_dinozaurilor_10939_3.jpg'),
	 ('Parking Garage and Car Wash',99.99,0,0.0,2,112,'Coming soon','Looking for a skill-building, imagination-boosting car toy for toddlers? The all-in-one LEGO® DUPLO® Parking Garage and Car Wash (10948) is packed with activities for car-loving toddlers.

Creative fun at the car-care complex
This versatile, vehicle playset includes a drive-through car wash, charging station, ramp, parking spaces, boom barrier, a place to clean the car by hand, 2 cars (1 with a mechanical Push&Go feature) and a camper van with room for 3 figures inside and equipment on the roof, plus accessories and characters (2 men, a grandmother, a child and a dog) to inspire endless imaginative play. And while kids are exploring the endless play possibilities, they’re developing essential skills that will last a lifetime.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they build together.',7,'http://localhost:5000/images/Garaj_si_spalatorie_de_masini_10948_1.jpg','http://localhost:5000/images/Garaj_si_spalatorie_de_masini_10948_2.jpg','http://localhost:5000/images/Garaj_si_spalatorie_de_masini_10948_3.jpg');
INSERT INTO onlinestore.product (name,price,discount,rating,age,piece_count,availability,description,theme_id,picture_url1,picture_url2,picture_url3) VALUES
	 ('Horse Stable and Pony Care',29.99,0,10.0,2,65,'Available now','LEGO® DUPLO® Town Horse Stable and Pony Care (10951) has everything a little animal lover needs to care for 2 adorable ponies. The imaginative fun and playful learning will never end.Play-and-learn pony stableIt’s always a fun-packed play-day at the pony stable. The 2 cute ponies need feeding before being taken out for a ride. Then they’ll want to have a drink and be brushed. Don’t forget to prepare a cozy place for them to sleep. As they take care of the ponies in the iconic stable, little animal lovers boost their preschool development, particularly fine motor skills and social and emotional awareness.Hands-on educational toys for toddlersLEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/grajdul_poneilor_10951_1.jpg','http://localhost:5000/images/grajdul_poneilor_10951_2.jpg','http://localhost:5000/images/grajdul_poneilor_10951_3.jpg'),
	 ('Race Cars',49.99,0,0.0,2,44,'Coming soon','LEGO® DUPLO® Town Race Cars (10947) is a colorful racetrack playset bursting with role-play fun and developmental benefits for little drivers.

Activity-packed race-car playset
The developmental play is fast and fun with this colorful car-race playset. 2 push-and-go cars and lots of accessories inspire endless racetrack role play. Clean the cars, charge them up, position the cones, wave the flags to start the race… and go! When the race is over, rebuild the set as a podium for the drivers to celebrate together with a trophy. An ideal toy to share with parents, siblings and friends – supporting preschoolers’ social and emotional learning as well as their creative and fine motor skills.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/Masini_de_curse_10947_1.jpg','http://localhost:5000/images/Masini_de_curse_10947_2.jpg','http://localhost:5000/images/Masini_de_curse_10947_3.jpg'),
	 ('Amusement Park',99.99,0,0.0,2,95,'Coming soon','Join your toddler on an imaginative trip to the LEGO® DUPLO® Town Amusement Park (10956) and explore an amazing mix of attractions designed to engage, entertain and stimulate growing minds.

Family fun at the fair!
Join 7 DUPLO characters – 2 women, 1 man and 4 children – for colorful, captivating developmental fun at the fairground! This multifaceted toy features slides to whizz down, a mechanical carousel to ride, a large Ferris wheel with 3 colorful cabins to operate, a train to drive around the park, hot dogs to buy, plus an ice cream, camera, balloons, cupcakes, broom and teddy bear. There’s even a color-changing ‘rainbow’ light to create an authentic funfair atmosphere.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they build together.',7,'http://localhost:5000/images/Parc_de_distractii_10956_1.jpg','http://localhost:5000/images/Parc_de_distractii_10956_2.jpg','http://localhost:5000/images/Parc_de_distractii_10956_3.jpg'),
	 ('Batcave™',29.99,0,9.0,2,33,'Available now','When THE JOKER™ escapes from jail, your little super hero joins Batman™ and Robin™ as they try to capture him and put him back where he belongs. This means lots of fun-packed action, imaginative role play and a chance for toddlers to develop super-power skills!

Developmental play with Batman and Robin
LEGO® DUPLO® Batman Batcave™ (10919) features Batman, Robin and THE JOKER in a versatile playset designed to encourage creative play and stimulate developmental benefits. Infants build fine motor skills as they maneuver the Batmobile™ toy through the gate and open and close the jail door. Role-playing the interaction between the 3 characters encourages social and emotional development.

Iconic characters and endless, pretend-play action
Featuring favorite super heroes and Super-Villains, cool gadgets and amazing vehicles, LEGO DUPLO Batman starter sets provide toddlers with endless developmental play and give parents an opportunity to share precious moments with their little superhero.',7,'http://localhost:5000/images/pestera_batman_10919_1.jpg','http://localhost:5000/images/pestera_batman_10919_2.jpg','http://localhost:5000/images/pestera_batman_10919_3.jpg'),
	 ('Minnie''s Birthday Party',19.99,0,10.0,2,21,'Out of stock','Features a party venue with an opening window, table, chair and buildable birthday cake, plus a car. Accessory elements include a Minnie Mouse portrait tile for the wall and 2 bricks decorated as birthday gifts. Preschoolers will love to build the cake and help Figaro throw an amazing party for Minnie Mouse.',7,'http://localhost:5000/images/petrecerea_lui_minnie_10873_1.jpg','http://localhost:5000/images/petrecerea_lui_minnie_10873_2.jpg','http://localhost:5000/images/petrecerea_lui_minnie_10873_3.jpg'),
	 ('Animal Train',19.99,0,10.0,2,15,'Available now','All kids love animals, right? So give a toddler the perfect introduction to the animal kingdom with LEGO® DUPLO® My First Animal Train (10955).

Pull-along animal parade toy
There’s lots for little animal lovers to do with the elephant, tiger, giraffe and panda. As they build and rebuild, line up the carriages, place animals on and off the train and stack them on top of each other, they develop fine motor skills and explore a magical world of imaginative role play. Innovative features, like the giraffe’s wobbling neck, add extra joy to this playful learning toy. Building cards, with life-size images of the models, let kids position the bricks over the image as they build. For even more fun, kids can connect the train to other wheel-based DUPLO toys.

Hands-on kids'' learning toys
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands. With DUPLO playsets, parents and toddlers can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/primul_meu_tren_cu_animale_10955_1.jpg','http://localhost:5000/images/primul_meu_tren_cu_animale_10955_2.jpg','http://localhost:5000/images/primul_meu_tren_cu_animale_10955_3.jpg'),
	 ('Number Train',19.99,0,10.0,2,23,'Available now','Introduce STEM toys early with the LEGO® DUPLO® Number Train. It’s a colorful introduction to numbers and counting. Your toddler will love to build and rebuild this developmental toy, learning early number recognition as they go! This set is the perfect educational gift for little ones and a great introduction to the LEGO STEM sets. With two child DUPLO® figures and a cat figure, the set provides endless storytelling and creativity for little minds. If you’re looking for a learning toy or STEM gift, the Number Train is your best bet, and DUPLO® bricks are designed to be safe and suitable for little hands.',7,'http://localhost:5000/images/trenul-cu-numere-10847_1.jpg','http://localhost:5000/images/trenul-cu-numere-10847_2.jpg','http://localhost:5000/images/trenul-cu-numere-10847_3.jpg'),
	 ('Steam Train',59.99,0,7.0,2,59,'Available now','The LEGO® DUPLO® 10874 Steam Train is now even easier for your toddler to control and interact with in multiple ways. Young children can become the train driver with the Push & Go motor — a gentle push either forwards or backwards sends the train on its way and a firm hold or lift off the tracks will make it stop. Help them place the 5 colored action bricks along the track to sound the horn, turn the lights on and off, pause and refuel, change direction and stop the train wherever they like. With a train station, coal tipper, 2 DUPLO figures plus an animal figure and a simple toy train track included in this LEGO DUPLO set, preschoolers can enjoy classic, fun train play. Download the optional app to unlock even more play possibilities, including remote-control function and fun activities to complete with your toddler!',7,'http://localhost:5000/images/trenulet_cu_aburi_10874_1.jpg','http://localhost:5000/images/trenulet_cu_aburi_10874_2.jpg','http://localhost:5000/images/trenulet_cu_aburi_10874_3.jpg');