INSERT INTO onlinestore.product (name,price,discount,rating,age,piece_count,availability,description,theme_id,picture_url1,picture_url2,picture_url3) VALUES
	 ('Dubai',59.99,0,4.5,16,740,'Available now','Share a photo of your favorite LEGO creations, we''d love to see how you''ve made it your own. Mention @lego on your Instagram posts to get your photo featured in our showcase.',1,'http://localhost:5000/images/dubai_21052_1.jpg','http://localhost:5000/images/dubai_21052_2.jpg','http://localhost:5000/images/dubai_21052_3.jpg'),
	 ('Paris',49.99,0,4.5,12,649,'Available now','Bring together iconic Paris landmarks with this magnificent Paris skyline model. The 21044 LEGO® Architecture Skyline Collection set features the Arc de Triomphe, Champs-Elysées, Tour Montparnasse, Grand Palais, Eiffel Tower and the Louvre, and is finished with grass and tree areas and a decorative Paris nameplate. This set has been designed to deliver a rewarding and relaxing building experience to all with an interest in architecture, travel, history and design, and makes a truly “magnifique” centerpiece for the home or office. Each skyline model is scaled to give an accurate representation of the comparative size of the featured structures, with realistic color depiction.',1,'http://localhost:5000/images/paris_21045_1.jpg','http://localhost:5000/images/paris_21045_2.jpg','http://localhost:5000/images/paris_21045_3.jpg'),
	 ('Taj Mahal',119.99,0,5.0,18,2022,'Available now','The Taj Mahal model features a wealth of rich details, including sweeping arches, ornate domes, soaring minarets and decorative finials. The LEGO Taj Mahal expert building kit can be build together with all other original LEGO sets and LEGO bricks, including other collectible building kits.',1,'http://localhost:5000/images/Taj_Mahal_21056_1.jpg','http://localhost:5000/images/Taj_Mahal_21056_2.jpg','http://localhost:5000/images/Taj_Mahal_21056_3.jpg'),
	 ('Farm Animal Care',9.99,0,5.0,2,11,'Upon order','The versatile LEGO® DUPLO® Town Farm Animal Care (10949) playset engages toddlers with imaginative play and encourages key developmental skills with the help of 4 adorable farm animals.

Build skills with toddler-friendly animals
Parents and toddlers will enjoy endless imaginative fun with the delightful pig, sheep, duck and cat. These 4 cute farm animals are perfect for preschoolers to pick up and play with. As they act out animal-care activities, such as feeding and preparing the barn for bedtime, little animal lovers will improve their fine motor skills and their social and emotional awareness.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/animalele_de_la_ferma_10949_1.jpg','http://localhost:5000/images/animalele_de_la_ferma_10949_2.jpg','http://localhost:5000/images/animalele_de_la_ferma_10949_3.jpg'),
	 ('Airplane & Airport',29.99,0,0.0,2,28,'Coming soon','Take a toddler''s imagination to a different destination every day with the LEGO® DUPLO® Town aeroplane & Airport (10961) toy. Share air-travel adventures with your preschooler Capture all the exciting adventures and family fun of a flight aboard a passenger aeroplane. Join a dad and his daughter as they fly off to see family and friends. The plane has a lift-off top section to reveal more space to play inside. The airport has an opening door and a turning control tower, a luggage slide and… big hugs waiting to greet your arrival! Hands-on educational toys for toddlers LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/Avion_si_aeroport_10961_1.jpg','http://localhost:5000/images/Avion_si_aeroport_10961_2.jpg','http://localhost:5000/images/Avion_si_aeroport_10961_3.jpg'),
	 ('Spider-Man Headquarters
',29.99,0,0.0,2,36,'Coming soon','LEGO® DUPLO® Marvel Spider-Man Headquarters (10940) is the perfect treat for a budding superhero. With 3 superhero figures and lots of super-fun activities, this versatile playset delivers excellent play value.

Fun-packed action with Spider-Man and friends
Based on the Disney+ TV show, Spidey and His Amazing Friends, this toddler-friendly superhero set combines the fun and adventure of the TV program with the hands-on, developmental benefits of LEGO DUPLO construction. The set features 3 superheroes – Spider-Man, Miles Morales and Ghost Spider – in their spider-shaped headquarters with fun accessories to inspire imaginative role play, including a motorcycle, slide and a rope swing.

Hands-on, imaginative role-play toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands, so parents and toddlers can share many precious developmental moments together.',7,'http://localhost:5000/images/Cartierul_general_al_Omului_Paianjen_10940_1.jpg','http://localhost:5000/images/Cartierul_general_al_Omului_Paianjen_10940_2.jpg','http://localhost:5000/images/Cartierul_general_al_Omului_Paianjen_10940_3.jpg'),
	 ('Ariel''s Undersea Castle
',29.99,0,0.0,2,35,'Upon order','LEGO® DUPLO® │ Disney Ariel''s Undersea Castle (10922) entertains and stimulates young minds, developing social and emotional skills with a mermaid''s playground full of fun features and role-play stories.',7,'http://localhost:5000/images/castelul_lui_ariel_10922_1.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_2.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_3.jpg'),
	 ('Heart Box',19.99,0,3.0,2,80,'Available now','This exciting mix of LEGO® DUPLO® bricks is bursting with ideas and inspiration! As parents and toddlers build, play and build again, this imaginative learning toy will kickstart kids’ creative building and deliver developmental benefits that last a lifetime. Unleash kids'' creativity with this stimulating starter set Little hands can''t wait to get hold of the toddler-friendly bricks and start building. Simple instructions ensure the imaginative play starts without delay. There''s a house, ice cream, whale, flower, helicopter and duck Each easy-to-build model provides lots to talk about and imaginative stories to role-play. The creative fun continues as kids mix the bricks to build their own creations. Build valuable skills a first LEGO DUPLO set LEGO DUPLO playsets put open-ended play and self-expression into the hands of budding builders. With recognizable settings, familiar characters and toddler-friendly bricks, they inspire preschoolers with a boundless enthusiasm for playful learning.',7,'http://localhost:5000/images/castelul_lui_ariel_10922_1.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_2.jpg','http://localhost:5000/images/castelul_lui_ariel_10922_3.jpg'),
	 ('T. rex and Triceratops Dinosaur Breakout',29.99,0,0.0,2,36,'Coming soon','This LEGO® DUPLO® Jurassic World T. rex and Triceratops Dinosaur Breakout (10939) toy is packed with fun features and Jurassic World movie action that’ll make dinosaur-loving kids roar with delight.

Developmental dinosaur playset
When a T. rex bursts through the iconic gates of Jurassic World, preschool dinosaur fans must help Owen rescue the baby triceratops and take it to safety on his motorcycle. From the entrance''s opening gates to the T. rex''s opening mouth; the high-voltage fence to the cool motorcycle with room on the seat for Owen and the baby triceratops – this playset is bursting with exciting action and fun features that develop kids’ construction and creative-thinking skills and fuel their imaginations.

Hands-on, imaginative role-play toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands, so parents and toddlers can share many precious developmental moments together.',7,'http://localhost:5000/images/Evadarea_dinozaurilor_10939_1.jpg','http://localhost:5000/images/Evadarea_dinozaurilor_10939_2.jpg','http://localhost:5000/images/Evadarea_dinozaurilor_10939_3.jpg'),
	 ('Parking Garage and Car Wash',99.99,0,0.0,2,112,'Coming soon','Looking for a skill-building, imagination-boosting car toy for toddlers? The all-in-one LEGO® DUPLO® Parking Garage and Car Wash (10948) is packed with activities for car-loving toddlers.

Creative fun at the car-care complex
This versatile, vehicle playset includes a drive-through car wash, charging station, ramp, parking spaces, boom barrier, a place to clean the car by hand, 2 cars (1 with a mechanical Push&Go feature) and a camper van with room for 3 figures inside and equipment on the roof, plus accessories and characters (2 men, a grandmother, a child and a dog) to inspire endless imaginative play. And while kids are exploring the endless play possibilities, they’re developing essential skills that will last a lifetime.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they build together.',7,'http://localhost:5000/images/Garaj_si_spalatorie_de_masini_10948_1.jpg','http://localhost:5000/images/Garaj_si_spalatorie_de_masini_10948_2.jpg','http://localhost:5000/images/Garaj_si_spalatorie_de_masini_10948_3.jpg');
INSERT INTO onlinestore.product (name,price,discount,rating,age,piece_count,availability,description,theme_id,picture_url1,picture_url2,picture_url3) VALUES
	 ('Horse Stable and Pony Care',29.99,0,5.0,2,65,'Available now','LEGO® DUPLO® Town Horse Stable and Pony Care (10951) has everything a little animal lover needs to care for 2 adorable ponies. The imaginative fun and playful learning will never end.Play-and-learn pony stableIt’s always a fun-packed play-day at the pony stable. The 2 cute ponies need feeding before being taken out for a ride. Then they’ll want to have a drink and be brushed. Don’t forget to prepare a cozy place for them to sleep. As they take care of the ponies in the iconic stable, little animal lovers boost their preschool development, particularly fine motor skills and social and emotional awareness.Hands-on educational toys for toddlersLEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/grajdul_poneilor_10951_1.jpg','http://localhost:5000/images/grajdul_poneilor_10951_2.jpg','http://localhost:5000/images/grajdul_poneilor_10951_3.jpg'),
	 ('Race Cars',49.99,0,0.0,2,44,'Coming soon','LEGO® DUPLO® Town Race Cars (10947) is a colorful racetrack playset bursting with role-play fun and developmental benefits for little drivers.

Activity-packed race-car playset
The developmental play is fast and fun with this colorful car-race playset. 2 push-and-go cars and lots of accessories inspire endless racetrack role play. Clean the cars, charge them up, position the cones, wave the flags to start the race… and go! When the race is over, rebuild the set as a podium for the drivers to celebrate together with a trophy. An ideal toy to share with parents, siblings and friends – supporting preschoolers’ social and emotional learning as well as their creative and fine motor skills.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/Masini_de_curse_10947_1.jpg','http://localhost:5000/images/Masini_de_curse_10947_2.jpg','http://localhost:5000/images/Masini_de_curse_10947_3.jpg'),
	 ('Amusement Park',99.99,0,0.0,2,95,'Coming soon','Join your toddler on an imaginative trip to the LEGO® DUPLO® Town Amusement Park (10956) and explore an amazing mix of attractions designed to engage, entertain and stimulate growing minds.

Family fun at the fair!
Join 7 DUPLO characters – 2 women, 1 man and 4 children – for colorful, captivating developmental fun at the fairground! This multifaceted toy features slides to whizz down, a mechanical carousel to ride, a large Ferris wheel with 3 colorful cabins to operate, a train to drive around the park, hot dogs to buy, plus an ice cream, camera, balloons, cupcakes, broom and teddy bear. There’s even a color-changing ‘rainbow’ light to create an authentic funfair atmosphere.

Hands-on educational toys for toddlers
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers’ hands. With DUPLO playsets, parents and young children can share precious developmental milestones as they build together.',7,'http://localhost:5000/images/Parc_de_distractii_10956_1.jpg','http://localhost:5000/images/Parc_de_distractii_10956_2.jpg','http://localhost:5000/images/Parc_de_distractii_10956_3.jpg'),
	 ('Batcave™',29.99,0,4.5,2,33,'Available now','When THE JOKER™ escapes from jail, your little super hero joins Batman™ and Robin™ as they try to capture him and put him back where he belongs. This means lots of fun-packed action, imaginative role play and a chance for toddlers to develop super-power skills!

Developmental play with Batman and Robin
LEGO® DUPLO® Batman Batcave™ (10919) features Batman, Robin and THE JOKER in a versatile playset designed to encourage creative play and stimulate developmental benefits. Infants build fine motor skills as they maneuver the Batmobile™ toy through the gate and open and close the jail door. Role-playing the interaction between the 3 characters encourages social and emotional development.

Iconic characters and endless, pretend-play action
Featuring favorite super heroes and Super-Villains, cool gadgets and amazing vehicles, LEGO DUPLO Batman starter sets provide toddlers with endless developmental play and give parents an opportunity to share precious moments with their little superhero.',7,'http://localhost:5000/images/pestera_batman_10919_1.jpg','http://localhost:5000/images/pestera_batman_10919_2.jpg','http://localhost:5000/images/pestera_batman_10919_3.jpg'),
	 ('Minnie''s Birthday Party',19.99,0,5.0,2,21,'Out of stock','Features a party venue with an opening window, table, chair and buildable birthday cake, plus a car. Accessory elements include a Minnie Mouse portrait tile for the wall and 2 bricks decorated as birthday gifts. Preschoolers will love to build the cake and help Figaro throw an amazing party for Minnie Mouse.',7,'http://localhost:5000/images/petrecerea_lui_minnie_10873_1.jpg','http://localhost:5000/images/petrecerea_lui_minnie_10873_2.jpg','http://localhost:5000/images/petrecerea_lui_minnie_10873_3.jpg'),
	 ('Animal Train',19.99,0,5.0,2,15,'Available now','All kids love animals, right? So give a toddler the perfect introduction to the animal kingdom with LEGO® DUPLO® My First Animal Train (10955).

Pull-along animal parade toy
There’s lots for little animal lovers to do with the elephant, tiger, giraffe and panda. As they build and rebuild, line up the carriages, place animals on and off the train and stack them on top of each other, they develop fine motor skills and explore a magical world of imaginative role play. Innovative features, like the giraffe’s wobbling neck, add extra joy to this playful learning toy. Building cards, with life-size images of the models, let kids position the bricks over the image as they build. For even more fun, kids can connect the train to other wheel-based DUPLO toys.

Hands-on kids'' learning toys
LEGO DUPLO toys put open-ended fun, self-expression and joyful learning into preschoolers'' hands. With DUPLO playsets, parents and toddlers can share precious developmental milestones as they play together.',7,'http://localhost:5000/images/primul_meu_tren_cu_animale_10955_1.jpg','http://localhost:5000/images/primul_meu_tren_cu_animale_10955_2.jpg','http://localhost:5000/images/primul_meu_tren_cu_animale_10955_3.jpg'),
	 ('Number Train',19.99,0,5.0,2,23,'Available now','Introduce STEM toys early with the LEGO® DUPLO® Number Train. It’s a colorful introduction to numbers and counting. Your toddler will love to build and rebuild this developmental toy, learning early number recognition as they go! This set is the perfect educational gift for little ones and a great introduction to the LEGO STEM sets. With two child DUPLO® figures and a cat figure, the set provides endless storytelling and creativity for little minds. If you’re looking for a learning toy or STEM gift, the Number Train is your best bet, and DUPLO® bricks are designed to be safe and suitable for little hands.',7,'http://localhost:5000/images/trenul-cu-numere-10847_1.jpg','http://localhost:5000/images/trenul-cu-numere-10847_2.jpg','http://localhost:5000/images/trenul-cu-numere-10847_3.jpg'),
	 ('Steam Train',59.99,0,3.0,2,59,'Available now','The LEGO® DUPLO® 10874 Steam Train is now even easier for your toddler to control and interact with in multiple ways. Young children can become the train driver with the Push & Go motor — a gentle push either forwards or backwards sends the train on its way and a firm hold or lift off the tracks will make it stop. Help them place the 5 colored action bricks along the track to sound the horn, turn the lights on and off, pause and refuel, change direction and stop the train wherever they like. With a train station, coal tipper, 2 DUPLO figures plus an animal figure and a simple toy train track included in this LEGO DUPLO set, preschoolers can enjoy classic, fun train play. Download the optional app to unlock even more play possibilities, including remote-control function and fun activities to complete with your toddler!',7,'http://localhost:5000/images/trenulet_cu_aburi_10874_1.jpg','http://localhost:5000/images/trenulet_cu_aburi_10874_2.jpg','http://localhost:5000/images/trenulet_cu_aburi_10874_3.jpg'),
	 ('Andy Warhol''s Marilyn Monroe',119.99,0,4.0,18,3341,'Available now','If you’re an Andy Warhol or Marilyn Monroe fan, this is the set for you. Recreate iconic art with this LEGO® Art Andy Warhol’s Marilyn Monroe (31197) set. Escape from everyday life with a relaxing activity and some focused me time.',2,'http://localhost:5000/images/andy_warhol_s_marilyn_monroe_31197_1.jpg','http://localhost:5000/images/andy_warhol_s_marilyn_monroe_31197_2.jpg','http://localhost:5000/images/andy_warhol_s_marilyn_monroe_31197_3.jpg'),
	 ('Wildlife Rescue ATV',9.99,0,5.0,5,74,'Upon order','Introduce budding explorers to the wonders of nature with this inspiring LEGO® City Wildlife Rescue ATV (60300) playset, featuring a cool toy all-terrain vehicle (ATV) with tilt-to-turn steering, equipped with a grabber tool and drone, plus a small savanna setting. Just add the explorer, monkeys and black scorpion for exciting animal-rescue adventures.

Great build-and-play experience for kids
This toy construction set comes with an easy-to-follow building guide and Instructions PLUS – part of the free LEGO Building Instructions app for smartphones and tablets. This interactive construction guide, with zoom and rotate viewing tools, helps young LEGO builders become master builders!',3,'http://localhost:5000/images/Atv_de_salvare_a_animalelor_salbatice_60300_1.jpg','http://localhost:5000/images/Atv_de_salvare_a_animalelor_salbatice_60300_2.jpg','http://localhost:5000/images/Atv_de_salvare_a_animalelor_salbatice_60300_3.jpg');
INSERT INTO onlinestore.product (name,price,discount,rating,age,piece_count,availability,description,theme_id,picture_url1,picture_url2,picture_url3) VALUES
	 ('Passenger Airplane',99.99,0,4.0,6,669,'Upon order','Children can launch creative play skyward with this LEGO® City Passenger Airplane (60262) building set, featuring a huge aircraft with seating for the pilot and passenger minifigures, including singer Poppy Starr from the LEGO City Adventures TV series. There''s even room onboard for Poppy''s red convertible automobile! Kids also get a terminal building complete with luggage conveyor and control tower, plus an airport truck with a vehicle elevator.

A cool airplane toy for kids
The LEGO City Passenger Airplane playset comes with an easy-to-follow building guide and Instructions PLUS – part of the free LEGO Building Instructions app for smartphones and tablets. This interactive building guide with zoom and rotate viewing tools helps budding LEGO builders become master builders.',3,'http://localhost:5000/images/avion_de_pasageri_60262_1.jpg','http://localhost:5000/images/avion_de_pasageri_60262_2.jpg','http://localhost:5000/images/avion_de_pasageri_60262_3.jpg'),
	 ('Family House',59.99,0,4.5,5,388,'Available now','The LEGO® City Family House (60291) has a lounge, kitchen, hobby room, bedroom, bathroom and lots of green-living features, including toy solar panels, charging station and a cool EV. Kids can expand this playset using the included Road Plates to create their own city. And with a family of minifigures, plus a Labrador retriever figure, there’s everything they need for hours of imaginative role play.A great build-and-play experience for kids aged 5 and upThis playset includes an easy-to-follow building guide and Instructions PLUS – part of the free LEGO Building Instructions app for smartphones and tablets. This interactive construction guide with zoom and rotate viewing tools quickly helps young LEGO builders become master builders.Awesome toys for boys and girlsLEGO City building sets stimulate open-ended role play based on real-life events, with feature-rich buildings, realistic toy vehicles and fun characters that deliver an enjoyable, fun-filled, build-and-play experience.',3,'http://localhost:5000/images/casa_familiei_60291_1.jpg','http://localhost:5000/images/casa_familiei_60291_2.jpg','http://localhost:5000/images/casa_familiei_60291_3.jpg'),
	 ('Town Center',99.99,0,3.0,6,790,'Available now','Kids get to dive into the LEGO® City Adventures TV series with this premium-quality LEGO City Town Center (60292) playset. There’s a toy pizza restaurant, recycling station, car wash, EV charging station, martial arts dojo and a park with a kids’ ride, plus fun LEGO City minifigure characters. And with the included LEGO City Road Plates, kids can connect to other playsets to expand their city – just the way they like it! A great gift for kids aged 6 and up. This playset comes with a simple building guide and Instructions PLUS – an interactive building guide with amazing zoom and rotate viewing tools that quickly help kids become master builders. Instructions PLUS is part of the free LEGO Building Instructions app for smartphones and tablets. The creative world of LEGO City! LEGO City playsets deliver an enjoyable build-and-play experience with feature-rich buildings, realistic vehicles and fun characters that stimulate imaginative, open-ended role play based on real-life events.',3,'http://localhost:5000/images/centrul_orasului_60292_1.jpg','http://localhost:5000/images/centrul_orasului_60292_2.jpg','http://localhost:5000/images/centrul_orasului_60292_3.jpg'),
	 ('Wildlife Rescue Off-Roader',49.99,0,5.0,4,157,'Upon order','Kids can become everyday heroes with this LEGO® City Wildlife Rescue Off-Roader (60301) playset, featuring an animal-rescue team including LEGO City Adventures TV series hero Jessica Sharpe, plus a lion, lion cub and a snake with its egg. Just add the river setting, toy water scooter and 4x4 to set the scene for exciting wildlife-rescue adventures.

Fun for all the family
LEGO 4+ sets deliver hours of fun for kids, friends and families. Each set comes with a simple building guide and a Starter Brick element to help youngsters along. And with 4+ sets, you also get Instructions PLUS – part of the LEGO Building Instructions app. This interactive building guide, with zoom and rotate viewing tools, really does make LEGO building child’s play.',3,'http://localhost:5000/images/Masina_de_teren_pentru_salvarea_animalelor_60301_1.jpg','http://localhost:5000/images/Masina_de_teren_pentru_salvarea_animalelor_60301_2.jpg','http://localhost:5000/images/Masina_de_teren_pentru_salvarea_animalelor_60301_3.jpg'),
	 ('Wildlife Rescue Operation',89.99,0,4.5,6,525,'Upon order','This multi-model LEGO® City Wildlife Rescue Operation (60302) playset is packed with awesome features, including a cool winch helicopter, tracked vehicle, savanna setting with landslide function and a veterinary station. Just add the toy elephants, crocodiles, monkey and rescue team for endless hours of exciting animal-rescue fun.

A great build-and-play experience for kids aged 6 and up
You’ll find easy-to-follow building instructions for this LEGO City set in the box. Or you can download Instructions PLUS, part of the free LEGO Building Instructions app for smartphones and tablets. This interactive construction guide, with amazing zoom and rotate viewing tools, quickly turns kids into master builders!',3,'http://localhost:5000/images/Operatiune_de_salvare_a_animalelor_salbatice_60302_1.jpg','http://localhost:5000/images/Operatiune_de_salvare_a_animalelor_salbatice_60302_2.jpg','http://localhost:5000/images/Operatiune_de_salvare_a_animalelor_salbatice_60302_3.jpg'),
	 ('Skate Park',39.99,0,4.5,5,195,'Available now','This LEGO® City Skate Park (60290) toy has everything kids need to stage exciting skating events, including a quarter pipe, ramp, seesaw and grind rail. Kids can also expand this playset to create their own city, via the included Road Plate. And with BMX rider, wheelchair athlete and skateboarder minifigures in the mix, endless hours of crowd-thrilling fun are guaranteed!Ideal for boys and girls aged 5 and upThis toy building set comes with an easy-to-follow building guide and Instructions PLUS– part of the free LEGO Building Instructions app for smartphones and tablets. This interactive construction guide with zoom and rotate viewing tools helps young LEGO builders become master builders.The creative world of LEGO CityLEGO City playsets deliver an exciting build-and-play experience. Kids play out stories that depict real life in a fun and imaginative way with feature-rich buildings, realistic vehicles and inspiring characters.',3,'http://localhost:5000/images/parc_de_skateboarding_60290_1.jpg','http://localhost:5000/images/parc_de_skateboarding_60290_2.jpg','http://localhost:5000/images/parc_de_skateboarding_60290_3.jpg'),
	 ('Main Square',199.99,0,3.0,6,1517,'Available now','Youngsters can dive right into the LEGO® City Adventures TV series with the amazing LEGO® City Main Square (60271) playset. There’s a city hall, city square, concert stage, classic diner and a tram station, plus cool toy vehicles including Mayor Fleck''s stretch limousine, Snake Rattler''s motorbike and Harl Hubbs'' handyman wagon. Add 14 minifigures, including an awesome lineup of LEGO City TV characters, and the scene is set for endless play.

City center playset for kids
The LEGO City Main Square playset comes with an easy-to-follow building guide and Instructions PLUS – part of the free LEGO Building Instructions app for smartphones and tablets. This interactive building guide with zoom and rotate viewing tools quickly helps young LEGO builders become master builders.',3,'http://localhost:5000/images/piata_principala_60271_1.jpg','http://localhost:5000/images/piata_principala_60271_2.jpg','http://localhost:5000/images/piata_principala_60271_3.jpg'),
	 ('Creative Blue Bricks',4.99,0,5.0,4,52,'Available now','An exciting mix of blue LEGO® bricks for kids, bursting with ideas and inspiration. As kids build, play and build again, this timeless building toy unlocks creative potential and delivers developmental benefits that last a lifetime. Kickstart creative building with a LEGO brick starter set Children aged 4 and over will love playing with the 3 easy-to-build LEGO toys. Simple instructions and fun features get the imaginative play started immediately. There''s a blue whale toy with big round eyes and a waterspout, a train toy with revolving wheels, and a mini robot toy with movable arms. The creative fun continues as kids mix the bricks to modify their models – then skyrockets as they produce endless imaginative creations of their own. Build valuable skills with LEGO bricks for kids LEGO Classic sets put open-ended play and self-expression in kids'' hands. And as they build, create and imagine, they develop skills that support future happiness and success.',4,'http://localhost:5000/images/caramizi_creative_albastre_11006_1.jpg','http://localhost:5000/images/caramizi_creative_albastre_11006_2.jpg','http://localhost:5000/images/caramizi_creative_albastre_11006_3.jpg'),
	 ('Creative Green Bricks',4.99,0,5.0,4,60,'Out of stock','This timeless building toy is bursting with ideas and inspiration in gorgeous green! As kids build, play and build again, it unlocks their imagination and encourages developmental skills that support future success. Boost creativity with this imaginative building bricks toy Introduce children aged 4 and over to creative construction with 3 easy-to-build LEGO® toys. There''s a cute green dog, a mini helicopter with rotating blades and an apple tree model with a delicious-looking detachable apple. The fun starts right away thanks to simple instructions and fun features. The imaginative play takes off as kids mix the bricks to modify their models, then soars as kids build inspired creations of their own. Build skills for the future with these bricks for kids LEGO Classic sets inspire boys and girls to build, create and imagine. As they enjoy endless open-ended play and creative self-expression, they develop valuable skills that last a lifetime.',4,'http://localhost:5000/images/caramizi_creative_verzi_11007_1.jpg','http://localhost:5000/images/caramizi_creative_verzi_11007_2.jpg','http://localhost:5000/images/caramizi_creative_verzi_11007_3.jpg'),
	 ('Bricks and Lights',29.99,0,5.0,5,441,'Upon order','Kids can get doubly creative with this fun LEGO® set. First by building cool models, and second by transforming them into shadow puppets using Light Brick Shadow Casters! From building bricks to shadow plays Kids aged 5 and up will be captivated when their mini-models become cool shadow images! Imaginations will run wild as images move, shrink and enlarge, inspiring endless storytelling activities. With 12 fun LEGO toys for kids to make – a castle, face, princess, bat, rooster, crook, pirate ship, owl, ghost, windmill, shark and a dinosaur – plus extra bricks to build creations of their own, anything can happen! And, when the 2 Shadow Casters come into action, the shadow plays never stop! Kids build skills as they design, display and create! LEGO Classic sets put ideas and inspiration into young hands. Simple guides for the fun models soon get kids started with their indoor activities. As they discover the joy of constructing creations of their own, they acquire skills that are key to future success.',4,'http://localhost:5000/images/caramizi_si_lumini_11009_1.jpg','http://localhost:5000/images/caramizi_si_lumini_11009_2.jpg','http://localhost:5000/images/caramizi_si_lumini_11009_3.jpg');
INSERT INTO onlinestore.product (name,price,discount,rating,age,piece_count,availability,description,theme_id,picture_url1,picture_url2,picture_url3) VALUES
	 ('Bricks and Wheels',39.99,0,0.0,4,653,'Available now','This impressive LEGO® Classic Bricks and Wheels (11014) toy building set makes a great gift for kids who love hands-on play. And with 9 inspiring wheel-themed build ideas in the box, plus lots of extra bricks and pieces, it’s sure to provide endless hours of creative fun for boys, girls, friends and families.

What''s in the box?
All kids need to create a model car, train, school bus, robot, skateboarding zebra, race car, bunny in a wheelchair, pull-along duck and a monkey on a banana skateboard.

Perfect for children aged 4 and up
Kids will love playing with these fun LEGO toys. And because every model comes with a simple construction guide and digital building instructions, even first-time builders get to experience the pride and joy of constructing their own LEGO toys.',4,'http://localhost:5000/images/caramizi_si_roti_11014_1.jpg','http://localhost:5000/images/caramizi_si_roti_11014_2.jpg','http://localhost:5000/images/caramizi_si_roti_11014_3.jpg'),
	 ('Medium Creative Brick Box',34.99,0,4.5,4,484,'Available now','Designed with builders of all ages in mind, this collection of LEGO® bricks in 35 different colors will encourage open-ended building play, and inspire any imagination. Windows, eyes, and lots and lots of wheels add to the fun and offer endless possibilities for creative construction and vehicle play. A great supplement set to any existing LEGO collection, this set comes in a convenient plastic storage box and includes ideas to get the building started.',4,'http://localhost:5000/images/cutie-medie-de-constructie-creativa-10696_1.jpg','http://localhost:5000/images/cutie-medie-de-constructie-creativa-10696_2.jpg','http://localhost:5000/images/cutie-medie-de-constructie-creativa-10696_3.jpg'),
	 ('Belle and the Beast''s Castle',79.99,0,5.0,6,505,'Available now','Magic and mystery await Disney’s Beauty and the Beast fans with this detailed LEGO® ǀ Disney Belle and the Beast’s Castle (43196) set. In addition to the castle, this set comes with printed picture instructions and digital Instructions PLUS. Using the LEGO Building Instructions app lets even younger builders feel like real master builders… awesome!

Wonderful characters start the play
This detailed set comes with Disney’s Beast (remove the Beast head to transform him into the Prince) and 2 Belle mini-doll figures, plus Philippe the horse, who Belle can ride, and 6 other well-known Beauty and the Beast LEGO figures. The set features several fun play starters that inspire kids to dive into their own imaginative world of magic and adventure.

Exciting role-play fun
Kids can play out their Disney Princess fantasies with this buildable toy set. The castle can be used on its own or with other LEGO sets for more fun story options. It makes a perfect on-trend gift or unique present for a young fan.',6,'http://localhost:5000/images/Castelul_lui_Belle_si_al_Bestiei_43196_1.jpg','http://localhost:5000/images/Castelul_lui_Belle_si_al_Bestiei_43196_2.jpg','http://localhost:5000/images/Castelul_lui_Belle_si_al_Bestiei_43196_3.jpg'),
	 ('Raya and the Heart Palace',79.99,0,5.0,7,610,'Available now','Adventure awaits Disney fans with this LEGO® ǀ Disney Raya and the Heart Palace (43181) set. The set comes with printed building instructions and digital Instructions PLUS! Using the LEGO Building Instructions app, the guided, real-life building process leaves even younger builders feeling like real master builders… awesome!

Appealing building details
The buildable palace has 6 different rooms to explore, including a throne room, treasure room and a hidden room behind a revolving wall. The 2 side towers open and can hold Raya’s and Namaari’s weapons. The central tower opens to reveal a bedroom, with portraits of Raya’s friends.

Exciting adventures
Kids can dive into playing with 2 mini-doll figures from Disney’s Raya and the Last Dragon – Raya and Namaari – plus Tuk Tuk and Namaari’s Serlot LEGO figures. The set makes a unique holiday gift and can be combined with LEGO ǀ Disney Raya and Sisu Dragon (43184) to create an ultimate Heart Palace construction toy set for the best role-play fun.',6,'http://localhost:5000/images/raya_si_palatul_inima_43181_1.jpg','http://localhost:5000/images/raya_si_palatul_inima_43181_2.jpg','http://localhost:5000/images/raya_si_palatul_inima_43181_3.jpg'),
	 ('Rapunzel''s Tower',59.99,0,5.0,6,369,'Available now','Exciting escapades await young Disney Princess fans in this delightful LEGO® ǀ Disney (43187) Rapunzel’s Tower set. The charming set includes a tower with a cave and secret room, plus extra play starters in 2 smaller builds.

Appealing, creative, construction fun
The detailed tower features 4 different rooms to explore, a hobby room, bedroom, cozy sitting room and a cave at the bottom with a secret door. There are also 2 smaller builds – a swing made from Rapunzel''s hair and The Snuggly Duckling tavern, complete with stool and piano, to encourage endless open-ended creative play.

Fun role-play adventures with beloved characters
Children can jump right into playing with this great set, which features 2 mini-doll figures-Disney’s Rapunzel and Flynn-plus a Pascal the chameleon LEGO figure for Disney. The set frees kids'' imaginations with different play starters, so kids can role-play their favorite Tangled movie scenes or come up with new ones.',6,'http://localhost:5000/images/Turnul_lui_Rapunzel_43187_1.jpg','http://localhost:5000/images/Turnul_lui_Rapunzel_43187_2.jpg','http://localhost:5000/images/Turnul_lui_Rapunzel_43187_3.jpg');