INSERT INTO onlinestore.theme (name,description,picture_url) VALUES
	 ('Arhitecture','LEGO® Architecture presents some of the iconic buildings of world architecture, all perfectly realized as LEGO models. From well-known buildings to more imaginative choices that still reflect architectural excellence, these will make a great addition to any desk, home or playroom.','http://localhost:5000/images/ARHICTECTURE.jpg'),
	 ('Art','The LEGO Art sets offer adults a new creative experience to help them relax and recharge as they transform a blank canvas (or in this case, small interlinking base plates) using LEGO tiles.','http://localhost:5000/images/ART.jpg'),
	 ('City','LEGO® City is a realistic LEGO world for your child to explore. Iconic vehicles and buildings form the backdrop to this bustling city, with everyday heroes catching bad guys and putting out fires. This is a world full of humor and charm that will really stimulate their creative imaginations.','http://localhost:5000/images/CITY.jpg'),
	 ('Classic','Develop children’s creativity with LEGO® Classic. Sets contain ideas to help them get started, while special pieces alongside classic LEGO bricks inspire even further. And because LEGO Classic spans so many different age groups, there’s fun for all the family and imagination for every generation.','http://localhost:5000/images/CLASSIC.jpg'),
	 ('Creator','The LEGO® Creator series lets your child experiment with houses, cars, planes and creatures. Sets can be rebuilt three ways, so there’s no limit to the fun. With LEGO Creator 3-in-1 sets, your child also gets to choose between 3 exciting builds for even more build and play fun.','http://localhost:5000/images/CREATOR.jpg'),
	 ('Disney','LEGO® Disney characters such as Moana and Elsa along with princesses including Cinderella, Ariel, and Rapunzel will come to life as your child recreates romance, adventure, and heroism. LEGO® Disney has all the elements such as castles, towers, a carriage, treasure chests, gateways, and more for your child to play out these classic stories and inspire them to build their own fairytales.','http://localhost:5000/images/DISNEY.jpg'),
	 ('Duplo','For 50 years, we have been introducing DUPLO® sets to little builders with big imaginations.','http://localhost:5000/images/DUPLO.jpg'),
	 ('Hidden','Lego Hidden Side was a Lego product line that was designed to provide an experience that combines both physical and digital play. This has been described by The Lego Group as "fluid play". The Hidden Side theme involved traditional brick built playsets, but combined them with augmented reality.','http://localhost:5000/images/HIDDEN.jpg'),
	 ('Minecraft','Stimulate children’s creativity with LEGO® Minecraft™, based on the best-selling online game. Brick by brick, the amazing world of Minecraft™ with its unique characters and landscapes is recreated here in LEGO bricks, so children can create their own exciting Minecraft™ stories.
','http://localhost:5000/images/MINECRAFT.jpg'),
	 ('Minions','Bring Gru’s lovable henchmen to life with new Minions playsets.
','http://localhost:5000/images/MINIONS.jpg');
INSERT INTO onlinestore.theme (name,description,picture_url) VALUES
	 ('Ninjago','LEGO® Ninjago™ is an exciting world of ninjas battling against the forces of evil. Your child will enjoy meeting their heroes and role-playing their exciting and varied adventures. In addition, they can play out the hit TV series and play against their friends in a battle to become the Master of Spinjitzu!','http://localhost:5000/images/NINJAGO.jpg'),
	 ('Speed Champions','LEGO® Speed Champions puts children in the driving seat as they race cars by the likes of McLaren, Porsche and Ferrari. Prepare cars to race and swerve around other drivers to take the chequered flag! Help them live out racing dreams with these authentic and super-fast cars.','http://localhost:5000/images/SPEEDCHAMPIONS.jpg'),
	 ('Super Mario','Bring your favorite character into the real world with LEGO® Super Mario™ playsets! Get started with the Adventures with Mario Starter Course, featuring LEGO® Mario™ – he can react in a great variety of ways as he takes on enemies and collects coins. Rearrange the course and combine with Expansion Sets to build your own levels and compete against your friends. And explore the LEGO Super Mario app for cool digital building tools, great gameplay ideas and to share your awesome creations!','http://localhost:5000/images/SUPERMARIO.jpg'),
	 ('Tehnic','LEGO® Technic provides a real challenge for experienced LEGO builders. With LEGO Technic elements, your child can build advanced, real-life functions like gearboxes, working piston engines, steering systems and working crane arms. These exciting sets will take their imaginations to the next level.
','http://localhost:5000/images/TEHNIC.jpg'),
	 ('Trolls','Open up a world of music and adventure for Trolls fans with colorful and playful sets that bring characters from the DreamWorks films to life. With sets that inspire the imagination and offer kids endless possibilities for role-play, LEGO® Trolls World Tour sets are sure to delight and entertain Trolls fans of all ages.','http://localhost:5000/images/TROLLS.jpg'),
	 ('VIDIYO','Drop a beat! VIDIYO is an exciting digital play experience in collaboration with Universal Music Group that lets kids bring their original music video creations to life using the songs they like from the artists they love.
','http://localhost:5000/images/VIDIYO.jpg');